version: 2

sources:
  - name: lojze
    description: "Data lake containing processed data from API sources."
    database: lojze
    schema: jezero
    tables:
      - name: cerif_research_area
        description: "CERIF research areas."
      - name: eutopia_institution
        description: "EUTOPIA institutions."
      - name: orcid_member_person
        description: "ORCID member person section containing external author identifiers."
      - name: orcid_member_works
        description: "ORCID member works section containing publication data."
      - name: orcid_member_works_parsed
        description: "ORCID member works section containing publication data - JSON parsed."
      - name: orcid_member_employments
        description: "ORCID member employments section containing affiliation data."
      - name: orcid_modified_member
        description: "ORCID members by modification date."
      - name: crossref_publication
        description: "Crossref publications."
      - name: crossref_publication_parsed
        description: "Crossref publications parsed."
      - name: crossref_top_n_research_area_publication
        description: "Top N CERIF research area publications from Crossref."
      - name: elsevier_publication
        description: "Elsevier publications."
      - name: elsevier_publication_parsed
        description: "Elsevier publications parsed."
      - name: elsevier_publication_affiliation
        description: "Elsevier publication affiliations."