version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_container
    environment:
      - POSTGRES_DB=lojze
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5000:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo_elsevier:
    image: mongo:4.4.6  # Last version that does not require AVX
    container_name: mongo_elsevier_container
    env_file:
      - .env
    ports:
      - "27000:27017"
    restart: always
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - /home/eucollab/dump/unzipped:/dump
      - mongo_data:/data/db
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: "/home/eucollab/postgres_data"
      o: bind
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: "/home/eucollab/mongo_data"
      o: bind

    #sudo docker volume rm $(sudo docker volume ls  | grep -v "ecr-luigi" | awk 'NR>1 {print $2}')