WITH src_datalake_orcid_member_employments AS (SELECT member_id,
                                                      member_employments,
                                                      row_created_at,
                                                      row_updated_at
                                               FROM {{ source('lojze', 'orcid_member_employments') }}),
     member_employment AS (SELECT m.member_id,
                                  es.value #>> '{employment-summary,put-code}'                     AS employment_id,
                                  es.value #>> '{employment-summary,organization,name}'            AS organization_name,
                                  es.value #>> '{employment-summary,organization,address,city}'    AS organization_city,
                                  es.value #>> '{employment-summary,organization,address,region}'  AS organization_region,
                                  es.value #>> '{employment-summary,organization,address,country}' AS organization_country,
                                  es.value #>> '{employment-summary,department-name}'              AS department_name,
                                  es.value #>> '{employment-summary,role-title}'                   AS role_title,
                                  COALESCE((es.value #>> '{employment-summary,start-date,year,value}')::INT,
                                           1)                                                      AS start_year,
                                  COALESCE((es.value #>> '{employment-summary,start-date,month,value}')::INT,
                                           1)                                                      AS start_month,
                                  COALESCE((es.value #>> '{employment-summary,start-date,day,value}')::INT,
                                           1)                                                      AS start_day,
                                  COALESCE((es.value #>> '{employment-summary,end-date,year,value}')::INT,
                                           2100)                                                   AS end_year,
                                  COALESCE((es.value #>> '{employment-summary,end-date,month,value}')::INT,
                                           1)                                                      AS end_month,
                                  COALESCE((es.value #>> '{employment-summary,end-date,day,value}')::INT,
                                           1)                                                      AS end_day
                           FROM src_datalake_orcid_member_employments AS m,
                                LATERAL JSONB_ARRAY_ELEMENTS(member_employments) AS e,
                                LATERAL JSONB_ARRAY_ELEMENTS(e -> 'summaries') AS es)
SELECT member_id,
       employment_id,
       CONCAT_WS('_',
                 organization_name,
                 organization_city,
                 organization_region,
                 organization_country,
                 department_name,
                 role_title)                                          AS affiliation_identifier,
       organization_name,
       organization_city,
       organization_region,
       organization_country,
       department_name,
       role_title,
       {{ safe_make_date('start_year', 'start_month', 'start_day') }} AS start_dt,
       {{ safe_make_date('end_year', 'end_month', 'end_day') }}       AS end_dt
FROM member_employment
